### ISSUE TITLE
feature requests : homophonic input (cantonese/mandarin) for character amnesia

### ISSUE THREAD

**Issue by Thomasc5** [tobychui/cyinput#12]
Not sure if these databases help:

Unihan Database
https://unicode.org/charts/unihan.html

開放資料授權協議
https://words.hk/base/hoifong/

**Comment by tobychui** [comment]
Feature usable in 14-6-2019 Updates.
![2019-06-14_23-18-37](https://user-images.githubusercontent.com/24617523/59520150-efa4c800-8efb-11e9-8faa-c5c59535e37b.png)
If you have time, feel free to help tidy up the database for the homophonic key value pairs. This will help others to find the word they need with more efficiency. Thank you for your support :)
