### ISSUE TITLE
【Bug】㗎字打不到

### ISSUE THREAD

**Issue by guyxyz** [tobychui/cyinput#20]
正常輸入676 再按10次下一頁會有個㗎字在左下角，但打出後那個字會出空白或方塊字，但輸入246再在架字以同音字方式找㗎字才能成功輸出。

**Comment by tobychui** [comment]
你可，請問你可以截圖並上載到這裡讓我看看嗎？看來我無法在我的系統上 reproduce 同樣的問題。

**Comment by tobychui** [comment]
在我的系統上測試的結果如下：
![ezgif-2-7768df69d1fd](https://user-images.githubusercontent.com/24617523/59559235-6d202380-9035-11e9-8bd6-75c7b7f5691e.gif)

**Comment by guyxyz** [comment]
我是輸入676 再按10次下一頁，之後輸入1字後在記事本上出空白字，chrome上會出方塊字，現在要輸入這個字只能用同音字才能正常打出來。

**Comment by tobychui** [comment]
> 
> 
> 我是輸入676 再按10次下一頁，之後輸入1字後在記事本上出空白字，chrome上會出方塊字，現在要輸入這個字只能用同音字才能正常打出來。

請問你的作業系統是甚麼版本和語言？ 是否已經安裝 MingLiU_HKSCS 字體？

**Comment by tobychui** [comment]
在 Big5 Windows 7 上面能夠 Reproduce 了。屬字庫編碼問題，將會在下一個版本處理。

**Comment by guyxyz** [comment]
作業系統windows10 1903繁體中文專業版，可以正常顯示香港中文字，即邨 嗰 啲這類字。
https://mega.nz/#!R19VQYrT!hX5k9pGodqcgpWtKlUtV9B1HyRiJe6YiXM6Dc7g4dvI
為了方便說明，我附上了影片檔。

**Comment by hkben** [comment]
just found a website , I think it can help to solve the issues

http://code.web.idv.hk/hkscs/hkscs.php?i=1

**Comment by guyxyz** [comment]
另又發現一個問題，在某些修圖軟件打字會完全失效，目前測試了Photoshop CS6和PhotoImpact都會有這個問題，無論如何還是要感謝你熱心製作這個軟件。
https://mega.nz/#!9ocxgKwR!oE_TFkE35jFAvSJclNeWfpfS2AppYtDSKsL9qo6XmDY
附上測試有問題的影片檔。

**Comment by tobychui** [comment]
> 
> 
> 另又發現一個問題，在某些修圖軟件打字會完全失效，目前測試了Photoshop CS6和PhotoImpact都會有這個問題，無論如何還是要感謝你熱心製作這個軟件。
> https://mega.nz/#!9ocxgKwR!oE_TFkE35jFAvSJclNeWfpfS2AppYtDSKsL9qo6XmDY
> 附上測試有問題的影片檔。

看了你的影片應該是 key hooking 出了問題（簡單來說是 cyinput 無法取得你的數字鍵使用權限）。 這屬於另一個 bug，如果方便的話請開一個新 Issue（並注明作業系統、程式版本等資料），謝謝。

**Comment by tobychui** [comment]
> 
> 
> 另又發現一個問題，在某些修圖軟件打字會完全失效，目前測試了Photoshop CS6和PhotoImpact都會有這個問題，無論如何還是要感謝你熱心製作這個軟件。
> https://mega.nz/#!9ocxgKwR!oE_TFkE35jFAvSJclNeWfpfS2AppYtDSKsL9qo6XmDY
> 附上測試有問題的影片檔。
在 Windows 7 Big5 系統上使用 Photoshop CS5 測試看起來沒有問題
你有試過重新啟動 cyinput / 更換輸入模式到 經剪貼簿嗎？
![2019-06-17_10-54-25](https://user-images.githubusercontent.com/24617523/59575598-c1d3a500-90ee-11e9-848d-414d8e7f22d9.png)

**Comment by tobychui** [comment]
This particular bug has been fixed in the latest version of cyinput. However, there are still more chars that has not been converted to latest UTF8 standards. (See image for detail). I will not close this issue first until problem is completely fixed.
![2019-06-17_18-31-25](https://user-images.githubusercontent.com/24617523/59598463-ce77ed80-912e-11e9-911d-d797cd9a3ae0.png)
