### ISSUE TITLE
【Enhancement】希望加入上一頁功能

### ISSUE THREAD

**Issue by guyxyz** [tobychui/cyinput#21]
有時想輸入的字在最尾一頁的話要按很多次下一頁才能成功輸入，例如麘字要按17次下一頁…
如果可以加入上一頁功能選字便方便很多了。

**Comment by tobychui** [comment]
你可以使用數字鍵盤上的 "-" （減）號來進行上一頁選取。請見 issue #2

**Comment by tobychui** [comment]
已在 README 加入換頁說明，希望能讓更多人了解此功能的存在。
