### ISSUE TITLE
【Bug】一些修圖軟件打字失效

### ISSUE THREAD

**Issue by guyxyz** [tobychui/cyinput#22]
我測試過Photoshop CS6還有PhotoImpact均失效，Photoshop CS5正常可用，已試過重開修圖軟件，重開輸入法。
Windows10繁體中文專業版版本1903 18362.175
Photoshop CS5版本2.0 (12.0x20100407 [20100407.r.1103 2010/04/07:14:00:00 cutoff; r branch]) x32
Photoshop CS6版本13.0(13.0 20120315.r.428 2012/03/15:21:00:00) x32
PhotoImpact版本12.00.4015.0
同樣附上影片檔說明情況:https://mega.nz/#!g50iwCxL!UsTHYO3k1yS6y_ZRpSjC-3DaK-njCdjNLHg-jZKPkp0
Photoshop CS6是在這裡下載的:https://mega.nz/#!XA4ATSAA!_ob4sSKGkX7VljOEpuM3BPkx0UPDpMPLSY8XYdvdilg
PhotoImpact 12:https://mega.nz/#!8ssWRQDS!6R7zMCGPvOWOUlZcEnAv6rOuvxxLY5x0icTT6sCn4C4

**Comment by guyxyz** [comment]
我安裝windows7再次測試後可以正常使用，應該是windows10的問題了…

**Comment by tobychui** [comment]
看起來是 Windows 10 個別版本的問題。我這邊無法 Reproduce。請嘗試 / 等待下一個版本的 Windows 更新，如果 Windows 版本更新後問題還存在請重新要求開啟本 Issue，謝謝。
