### ISSUE TITLE
【Bug】隱藏輸入視窗問題

### ISSUE THREAD

**Issue by guyxyz** [tobychui/cyinput#23]
不知這算不算bug，輸入法的視窗以正常縮放設定後，每次打完字按/鍵隱藏輸入視窗，下次要打字時再按/鍵顯示輸入視窗時都會變成選字欄，要先按一下.鍵取消才能打字。
附上影片檔說明:https://mega.nz/#!Ek8QgSaA!avMR_mCvlJNFE71SJ1UEYLHKNVKaO5Ondhos0wrPEAE

**Comment by tobychui** [comment]
One missing statement in the dotHandler. Fixed in the latest build.
![2019-06-17_21-07-08](https://user-images.githubusercontent.com/24617523/59606517-ee65dc00-9143-11e9-8cb6-cb5a0cf16617.png)
