### ISSUE TITLE
【Enhancement】香港字

### ISSUE THREAD

**Issue by Thomasc5** [tobychui/cyinput#27]
打一些常用香港字，例如「嘅」(6, 7, 7)，要按 "下一頁"  7次才能選到字

希望常用香港字能轉成紅色 (選字時較易看到)，又或可用 shortcut 直接能去到？ 例如: 打完 6, 7, 7 後，按  "*"， 能直接跳去相關香港字  (e.g. 嘅，吓)

Shortcut 只需包括一些常用香港字就可以，例如 "㗎、咗、嚟、嘅" 個類

Written Cantonese
https://en.wikipedia.org/wiki/Written_Cantonese

p.s.  希望 taskbar icon 能加入 version no. (e.g.  2019.6.21) 及 介面能有幾個顏色供自選

Thank you!

**Comment by tobychui** [comment]
你好，
有關於香港字轉紅色的一項，因為香港字的部分還沒能完全 UTF-8 化（部分香港字還停留在 BIG-5 編碼，需時間人手轉譯），因此在轉譯完成之前應該沒有辦法把香港字紅色化。

其他要求我們將會抽時間處理並改進，謝謝你的提議！

**Comment by tobychui** [comment]
在最新測試版本中已經加入不同顏色的界面以供選擇。
![2019-10-13_14-15-55](https://user-images.githubusercontent.com/24617523/66711754-72fbfa80-edc4-11e9-8c63-715ebd0cfe53.png)
![2019-10-13_14-15-28](https://user-images.githubusercontent.com/24617523/66711755-73949100-edc4-11e9-95b6-b77cfdbdc055.png)
