### ISSUE TITLE
【Bug】現在的版本在windows10上選字偏右了

### ISSUE THREAD

**Issue by guyxyz** [tobychui/cyinput#28]
之前有人回報win8.1選字欄會偏左，現在的新版本在windows10上用就變成偏右了…
https://mega.nz/#!JlckjQ6K!klyfvkfsvxaY8PWGz0n4bHZQHWmvn1q-48sfiNmCjBQ
附上圖檔說明問題。
Windows10繁體中文專業版版本1903 18362.175

**Comment by tobychui** [comment]
加入了對 Windows 8.1 only 的版本檢測和內核版本檢測，現在 Win 10 應該不會再有問題。如有問題請再要求重開這個 Issue ，謝謝。
