### ISSUE TITLE
可否加入CONF檔的功能

### ISSUE THREAD

**Issue by xos84292-hub** [tobychui/cyinput#29]
因為我放USB使用,在不同的電腦上使用, 在A電腦修改完設定到B電腦又要修改一次,如果可以加入選項,讓程式改以根目錄的conf檔而非登錄檔讀寫設定就更好了

anyway,感謝你的開發

**Comment by tobychui** [comment]
此功能已經在 1.94.7.0 版本之後加入到輸入法中，開啟方法如下：
在 Tray Menu 中找到 USB 模式 --> 點選啟動
![2019-08-16_14-11-37](https://user-images.githubusercontent.com/24617523/63147116-cc97b100-c02f-11e9-8a7d-cec5822ec736.png)

之後在 cyinput.exe 同一根目錄下會出現一個設定檔案，在另一台電腦使用時該設定檔案會優先載入並還原原有設定。
