### ISSUE TITLE
feature requests : 香港增補字庫

### ISSUE THREAD

**Issue by beamer7788** [tobychui/cyinput#3]
as title

**Comment by tobychui** [comment]
This request is work in progress by Ben (https://github.com/hkben).

**Comment by tobychui** [comment]
"香港增補字庫" added. Please update your cyinput for using these new characters. 
![test](https://user-images.githubusercontent.com/24617523/59173944-d1e50500-8b81-11e9-8b0a-75d7192d3b4c.PNG)
