### ISSUE TITLE
可否加入滑鼠/觸控直接點選的功能【Enhancement】

### ISSUE THREAD

**Issue by xos84292-hub** [tobychui/cyinput#30]
我在推廣這輸入法的時候,
發現有朋友是一直使用滑鼠或觸控螢幕點擊某方的輸入法介面,而不是使用NUM PAD
當他們發現速型並不支持這種方法,只好放棄了
(例如NOTEBOOK沒有獨立NUM PAD鍵又不想使用英文鍵代替NUM PAD, 或者是平板模式的WIN10電腦)

如可讓速型輸入法也支持使用滑鼠直接而不一定使用NUM PAD點擊就更完美了

**Comment by tobychui** [comment]
是的，這個也是我一直想加入去的功能，然而滑鼠直點而不會誤 focus 到輸入法視窗在技術上有一定難度，這個我要先研究一下。

**Comment by tobychui** [comment]
已於 1.111.2.0 版本更新加入此功能要求。
