### ISSUE TITLE
【Bug】無法轉換至標準界面

### ISSUE THREAD

**Issue by gtphil** [tobychui/cyinput#32]
我在Windows 10開啟輸入法，預設顯示為新版的迷你界面：
https://raw.githubusercontent.com/tobychui/cyinput/master/image/mini.png

在同類輸入法，我可以在迷你界面上按鍵，以轉換成標準界面。然而，這在此輸入法並不奏效。
我閱讀文檔，並沒有說明如何轉換至標準界面。而我嘗試了Numpad其他按鍵，也無法轉成標準界面。我沒法轉成標準界面，就沒法設定輸入法的行為。

**Comment by tobychui** [comment]
你可以在 開始功能表的 Tray Icon 上面找到視窗縮放選項。你看不到這個 Icon 可能是因為你的作業系統被設定成不顯示所有圖標。
![Uploading 2019-09-18_18-07-25.png…]()

請參閱以下教學以更改 Windows Tray icon 設定
https://winaero.com/blog/always-show-tray-icons-windows-10/
