### ISSUE TITLE
【Enhancement】九官格排版

### ISSUE THREAD

**Issue by lewisliiiii** [tobychui/cyinput#38]
想問可唔可以改到揀唔同版本嘅九官格排版？因為現時由 2000 年版本轉過嚟有啲唔習慣啲標點同埋啲字位。

**Comment by tobychui** [comment]
你好，因為我們現在所用的字庫（即你所說的排版）是自行開發而且經我方改良過，所以如果要在正式發佈版本中讓用家選擇多於一個排版會令到整個輸入法有一定程度的維護困難。如果你有編程經驗的話我會建議你 Fork 一個版本出來自行重組字庫。
所以非常抱歉我們並沒有辦法滿足此項功能要求。
