### ISSUE TITLE
【Bug】顯示輸入法問題

### ISSUE THREAD

**Issue by guyxyz** [tobychui/cyinput#39]
以正常尺寸顯示輸入法，當隱藏輸入法視窗時用滑鼠右鍵按通知欄的Cy>視窗設定>顯示/隱藏來顯示輸入法視窗後便會變成圖中這樣，但按/鍵來顯示的話就沒有問題。
![image](https://upload.cc/i1/2019/10/18/qgPXpb.jpg)

**Comment by tobychui** [comment]
Fixed in latest release
