### ISSUE TITLE
[QUESTION] Unable to push

### ISSUE THREAD

**Issue by roylau134** [tobychui/cyinput#4]
cant push

**Comment by roylau134** [comment]
request push right
thx

**Comment by tobychui** [comment]
Please fork the repo, modify the code and then create a pull request to request merging your code into the main branches. The is needed because  I have to review the code before the code is actually pushed into the main branch and check if there are bugs or any suspicious functions. Many thanks!

**Comment by roylau134** [comment]
em....
i think best practices is letting me to directly create and push to branches. Then i will submit a merge request on this repo.
In this case, you will still able to see my changes and hv full control on the master.

**Comment by tobychui** [comment]
That would be nice! I have created a new branch for you. Please check if you can push to that branch instead. Thanks :)

**Comment by roylau134** [comment]
I just test to push those changes on `experimental`. 
is was stated 
```
ERROR: Permission to tobychui/cyinput.git denied to roylau134.
fatal: Could not read from remote repository.
```

**Comment by tobychui** [comment]
Please accept the collaborator request and try again. Thanks.
