### ISSUE TITLE
【Enhancement】Backspace, Enter, Spacebar 按鍵

### ISSUE THREAD

**Issue by Thomasc5** [tobychui/cyinput#42]
朋友因病需點擊 onscreen keyboard 打字，他希望能在介面的上方或下方空間，加入 backspace, enter 及 spacebar 三個常用輸入按鍵 

Thank you!

![Capture](https://user-images.githubusercontent.com/5540385/67612597-789b0c80-f7d6-11e9-8aa6-5f1649b74e6b.JPG)

**Comment by tobychui** [comment]
已在最新測試版本中添加 on screen keyboard 的支援。
![2019-10-26_12-48-08](https://user-images.githubusercontent.com/24617523/67614534-46e36f00-f7f1-11e9-90c5-bf8593d462f9.png)
![2019-10-26_12-55-56](https://user-images.githubusercontent.com/24617523/67614535-477c0580-f7f1-11e9-9b19-5697abbc384e.png)
