### ISSUE TITLE
【Enhancement】Mobile Version

### ISSUE THREAD

**Issue by pigmich** [tobychui/cyinput#43]
會考慮開發 Android/ IOS 版嗎？謝謝！

**Comment by tobychui** [comment]
我曾考慮開發手機版，可是一來我們沒有這手機版的開發者，二來此輸入法是使用 VB.net 進行開發，移植上比較困難。
如果你有相關的資源或認識手機應用開發者，歡迎與我們聯絡，我們會很樂意提供相關的開發支援。
