### ISSUE TITLE
增加紅色版本

### ISSUE THREAD

**Issue by gusdapperton** [tobychui/cyinput#8]
https://resources.edb.hkedcity.net/inputway/cinput/graphics/cpt4_img02.gif

thanks~

**Comment by tobychui** [comment]
你好，我們這個輸入法是針對字型而設計的，並沒有打算支援其他輸入方式，不過還是謝謝你的提議 :) 。
English translation:
Hi there, our IME focus on searching for words with the shape of the word. There is no plan for adding one more method of word searching. Thanks for your ideas :)
