### ISSUE TITLE
[Enhancement] Request feature for keyboard button to show/hide input

### ISSUE THREAD

**Issue by mcmartin25** [tobychui/cyinput#9]
Please add a feature that show/hide the input window by pressing scroll lock on keyboard.

Please add this feature, thanks.

**Comment by tobychui** [comment]
Hi there! Thanks for your request :)
In the experimental build, we have added the "/" (keypad) button for toggling cyinput. You can also toggle the cyinput via the tray menu (See the attached image). We are expecting to release this in the next build.
![2019-05-19_23-12-21](https://user-images.githubusercontent.com/24617523/57984167-a5aafc80-7a8b-11e9-99fa-19c7464d9173.png)

**Comment by mcmartin25** [comment]
> Hi there! Thanks for your request :)
> In the experimental build, we have added the "/" (keypad) button for toggling cyinput. You can also toggle the cyinput via the tray menu (See the attached image). We are expecting to release this in the next build.
> ![2019-05-19_23-12-21](https://user-images.githubusercontent.com/24617523/57984167-a5aafc80-7a8b-11e9-99fa-19c7464d9173.png)
> 
> May I know if there are any particular reason to use the scroll lock key?

I am a q9 long-time user, and all q9 users (including me) need to use scroll key to hide/show input.

Just the way to make a more user-friendly keyboard shortcut for any q9 users to try to use it, because when I try this input, I can't find the shortcut key to show/hide the input, only can change the setting by click that option.

**Comment by tobychui** [comment]
As it has a bit difficulties to hook the key "scroll lock" and I also think using "/" on keypad to replace the scroll lock key is good enough for most of the purpose. How do you think about that?

**Comment by mcmartin25** [comment]
I think it's ok.

However, to avoid this situation, and make (new) users know there is a shortcut available, could it possible to add shortcut key text next to the text in the menu, such as the ShortcutKey property in Visual Studio? https://www.homeandlearn.co.uk/NET/nets4p4.html

**Comment by hkben** [comment]
Just my two cents.  I choose "Keypad /" instead of "scroll lock" when I was working on that feature for a personal reason.  I uses a KVM software , Synergy , that used "scroll lock" for company lock. Also , I heard some software uses "scroll lock" for some special feature , like MS excel . So I choose "Keypad /" for on-off.

**Comment by mcmartin25** [comment]
@hkben You're right.

@tobychui 
> However, to avoid this situation, and make (new) users know there is a shortcut available, could it possible to add shortcut key text next to the text in the menu, such as the ShortcutKey property in Visual Studio? https://www.homeandlearn.co.uk/NET/nets4p4.html

Review the topic that I posted few days ago, I made a graphic explanation just for everyone to easier to understand. For example, I put the shortcutkey property into "Show/Hide"(顯示/隱藏) setting with the "Alt+NumLock" shortcutkey (I can't find slash(/) for this property.) and showshortcutkey property set to true.

![exemple1](https://user-images.githubusercontent.com/45849014/58760074-cbdd9b80-8565-11e9-9aac-badebf8b5325.PNG)
![exemple2](https://user-images.githubusercontent.com/45849014/58760088-e3b51f80-8565-11e9-9b7c-e9e0a77ff05f.PNG)

This method also can be activate programmically.
However, I don't know if it works or not.

**Comment by tobychui** [comment]
> 
> 
> @hkben You're right.
> 
> @tobychui
> 
> > However, to avoid this situation, and make (new) users know there is a shortcut available, could it possible to add shortcut key text next to the text in the menu, such as the ShortcutKey property in Visual Studio? https://www.homeandlearn.co.uk/NET/nets4p4.html
> 
> Review the topic that I posted few days ago, I made a graphic explanation just for everyone to easier to understand. For example, I put the shortcutkey property into "Show/Hide"(顯示/隱藏) setting with the "Alt+NumLock" shortcutkey (I can't find slash(/) for this property.) and showshortcutkey property set to true.
> 
> ![exemple1](https://user-images.githubusercontent.com/45849014/58760074-cbdd9b80-8565-11e9-9aac-badebf8b5325.PNG)
> ![exemple2](https://user-images.githubusercontent.com/45849014/58760088-e3b51f80-8565-11e9-9b7c-e9e0a77ff05f.PNG)
> 
> This method also can be activate programmically.
> However, I don't know if it works or not.

Sure, I will take a look into this issue really soon.

**Comment by tobychui** [comment]
Function added in 17-6-2019 build.
![2019-06-17_19-57-14](https://user-images.githubusercontent.com/24617523/59602767-32ec7a00-913a-11e9-8f0c-110069cc27d7.png)
